# Generated by Django 3.2.12 on 2022-09-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='catagory',
            field=models.CharField(choices=[('sports', 'Sports'), ('electronics', 'Electronics'), ('technology', 'Technology'), ('movies', 'Movies'), ('science', 'Science'), ('music', 'Music'), ('exprience', 'Exprience'), ('general', 'General')], default='General', max_length=200),
        ),
    ]
