# Generated by Django 4.1 on 2022-10-06 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_replycomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replycomment',
            options={'ordering': ['-reply_date']},
        ),
    ]
