# Generated by Django 4.1 on 2022-10-06 07:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0016_alter_replycomment_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReplyComment',
            new_name='Reply',
        ),
    ]
