# Generated by Django 4.1.2 on 2022-12-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
