# Generated by Django 4.1.2 on 2022-12-09 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_post_videos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='articles',
        ),
    ]
