# Generated by Django 4.1.2 on 2023-01-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_rename_body_comment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='catagory',
            field=models.CharField(choices=[('sports', 'Sports'), ('technology', 'Technology'), ('entertainment', 'Entertainment'), ('science', 'Science'), ('other', 'Other'), ('fashion', 'Fashion')], max_length=200),
        ),
    ]
