# Generated by Django 4.1.2 on 2023-01-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_profile_telegram_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='media/image/defualt.png', upload_to='image'),
        ),
    ]
